CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    admin INTEGER NOT NULL CHECK (admin IN (0, 1)) DEFAULT 0
);